### ISSUE TITLE
Upgrading breaks 

### ISSUE THREAD

**Issue by JeroenvO** [modoboa/modoboa-stats#16]
Upgrading modoboa to 1.6.2 and stats to 1.0.10 breaks modoboa.
Using uwsgi with nginx
` python manage.py makemigrations
Illegal instruction`

I cannot find any further error messages in nginx or uwsgi. Website gives a gateway timeout.
when modoboa-stats is removed from the extensions, everything works as expected.

**Comment by tonioo** [comment]
How do you upgrade? When do you get this message?

**Comment by JeroenvO** [comment]
using `pip install -U mododoboa-stats`.
I upgraded mododobao from 1.6.1 to 1.6.2 and stats at the same time.
As shown, migration didn't work.
I tried it first in virtualenv and later directly on my host python with a clean install. Both gave this error.
Offcourse nginx and uwsgi were restarted in between.
on python 2.7.9 on debian 8;

**Comment by JeroenvO** [comment]
I just retried.
lxml is upgraded from 3.7.0 to 3.7.1.
re-enabling modoboa-stats in settings.py worked directly.
I don't know what exactly went wrong, but it works again.
