### ISSUE TITLE
Blank page in stats and js error in search

### ISSUE THREAD

**Issue by ToniRos** [modoboa/modoboa-stats#32]
Hello,

The stats page is always blank on a server with small (but some) traffic.

I verify the execution of  "python manage.py logparser --verbose"  without errors.

The rrd files are created in /tmp/modoboa and are accessible for apache server.

Server is CentOs 7 updated, with rrdtool installed

The js console in a browser shows this error when I search for a nonexisting domain.
TypeError: e is undefined jquery.min.js:3:5099

The versions are:
Statistics	1.2.2
Modoboa	1.9.1
Amavis frontend	1.1.3
Webmail	1.2.2

Some idea to look into?

Thanks.

**Comment by tonioo** [comment]
@ToniRos Can you check than rrdtool (the binary) is installed on your server?

**Comment by ToniRos** [comment]
# rpm -qa|grep rrdtool
rrdtool-devel-1.4.8-9.el7.x86_64
uwsgi-plugin-rrdtool-2.0.15-1.el7.x86_64
rrdtool-1.4.8-9.el7.x86_64
rrdtool-python-1.4.8-9.el7.x86_64

# rrdtool
RRDtool 1.4.8  Copyright 1997-2013 by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov 20 2015 19:23:48

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
                last, lastupdate, first, info, fetch, tune,
                resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages

**Comment by ToniRos** [comment]
Executed on the server.

**Comment by ToniRos** [comment]
OK, the correction of javascript solves the TypeError: e is undefined.

Thanks.

**Comment by ToniRos** [comment]
@tonioo , finally I found mentions.... 
I'm new to git. Sorry. The result of executing "rpm -qa|grep rrdtool", and "rrdtool" are above.

**Comment by tonioo** [comment]
@ToniRos you should not store rrd files in /tmp since they will be deleted after each reboot. Have you declared domains in Modoboa and do they receive traffic on this server?

**Comment by ToniRos** [comment]
@tonioo 
Destination changed to other path, but the server only purges tmp files older than a week.
The server receive traffic and I check one rrd of one domain with:
rrdtool dump file.rrd. Check data:
...
        <version>0003</version>
        <step>60</step> 
        <lastupdate>1510936440</lastupdate> 
...
                         <row><v>0.0000000000e+00</v><v>2.0833333333e-03</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.00
00000000e+00</v><v>2.9064583333e+01</v></row>
                         <row><v>0.0000000000e+00</v><v>2.0833333333e-03</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.0000000000e+00</v><v>0.00
00000000e+00</v><v>5.4325000000e+01</v></row>
...

Thanks.

**Comment by ToniRos** [comment]
@tonioo Finally the stats are shown.
I forced the recompilation of modoboa_stats/graphics.py deleting the pyc, and they start to work like a charm.

Thanks.
