### ISSUE TITLE
journald

### ISSUE THREAD

**Issue by genofire** [modoboa/modoboa-stats#41]
with systemd i prefer journald instatt of log-file/syslog

**Comment by tonioo** [comment]
@genofire Can you explain a bit more why you opened this issue?

**Comment by genofire** [comment]
At first, i do not use modoboa any more.
I just wanted to ask, if you could create another logging method.
(Not into a file)

**Comment by tonioo** [comment]
The file parsed to gather statistics is generated by postfix, it is not a modoboa issue.

**Comment by genofire** [comment]
**postfix** does it, but modoboa-stats could not read from journald ...
