### ISSUE TITLE
Statstistics graph show 2 times in page

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-stats#45]
# Impacted versions

* modoboa-stats version: 1.4.0
* Distribution: Debian
* Codename: Stretch
* Arch: 64 Bits
* Database: MariadDB

# Steps to reproduce

Just click on "Statistics" menu.

Problems:

The graph are printed two times.
Type of mail stay in French unless we switch to English.

![sc](https://user-images.githubusercontent.com/12907102/42307125-c2363914-8031-11e8-9308-e1a6aa71f9e7.png)

**Comment by tonioo** [comment]
The graphs are not printed two times, the smaller one lets you zoom in/out. Just select a zone in the smaller graph and it will update the main graph. Can you update the issue or open a new one about the translation?

**Comment by stefaweb** [comment]
Hi!

So stupid. I don't see that.

May be be some words below the second graph will help.  ;)

**Comment by tonioo** [comment]
I'll think about if for the documentation.
