### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by renarios** [modoboa/modoboa-stats#71]
Hi!

In the Modoboa statistics my graph is empty. When I mouse-over the graph, it gives an "Invalid date". 
![Modoboa-stats-invalid-date2](https://user-images.githubusercontent.com/12120817/167831278-6137ae2e-c75a-40f8-bce3-ba43508cde93.png)
When I issue an "rrdtool graph" command from cli, rrdtool plots a png file with valid date. 
![graph](https://user-images.githubusercontent.com/12120817/167831555-5885d7de-fdde-4431-b118-28fc0f105411.png)

How can I solve this issue?

Cheers, 
Rene

**Comment by tonioo** [comment]
@renarios What version of Modoboa are you using? This module is now deprecated since it has been merged to the core application. I should archive this repository...

**Comment by renarios** [comment]
@tonioo I installed a new Ubuntu 20.04 server with the latest Modoboa version: 20.0

**Comment by tonioo** [comment]
Have you checked the new UI? (to see if graphs are displayed properly)

**Comment by renarios** [comment]
You mean the "New admin"?  Yes, that look very cool, but I have no dashboard/graphs in the new UI:
![image](https://user-images.githubusercontent.com/12120817/167858496-641213fd-4721-4cb1-9692-0b4c59e2f15a.png)

**Comment by tonioo** [comment]
Yes new admin.
Graphs are only displayed per-domain right now so just choose one of your domains (one with trafic) and open its detail page.

**Comment by renarios** [comment]
Nice! Didn't know that. Looks awesome!
Thanks!

Will close this one
